version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app-container
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///database.db
      - SECRET_KEY=your_secret_key_here
      - PORT=5000
    volumes:
      - .:/app  # Mount the app directory to the container for live development
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
