apiVersion: apps/v1
kind: Deployment
metadata:
  name: catgifs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: danielkolodko/catgifs:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: catgifs-config
            - secretRef:
                name: catgifs-secret
