apiVersion: v1
kind: Service
metadata:
  name: catgifs-service
spec:
  type: LoadBalancer
  selector:
    app: catgifs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: catgifs-db-service
spec:
  selector:
    app: catgifs-db
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
